name: Export and branch solution

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    environment: Dev 

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          lfs: true
      
      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.APPLICATIONID }}
          client-secret: ${{ secrets.SECRETKEY }}
          tenant-id: ${{ secrets.TENANT }}

      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.APPLICATIONID }}
          client-secret: ${{ secrets.SECRETKEY }}
          tenant-id: ${{ secrets.TENANT }}
          solution-name: con_core_solution
          solution-output-file: solutions/con_core_solution.zip

      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.APPLICATIONID }}
          client-secret: ${{ secrets.SECRETKEY }}
          tenant-id: ${{ secrets.TENANT }}
          solution-name: con_core_solution
          solution-output-file: solutions/con_core_solution_managed.zip
          managed: true

      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: solutions/con_core_solution.zip
          solution-folder: deployment/con_core_solution }}
          solution-type: 'both'
          overwrite-files: true